In [1]:
#This program i am about to write will help to take input as student id and mark of the students, to calculate the 
#average of the scores of the students
#I am using while loop



In [2]:
def Students_info():
    
    "this function is to return a dictionary"
    
    D = {}
    
    while True:
        
        Students_id = int(input('enter students_id:'))
        Marks_sheet = input('enter students marks seperated by comma:')
        
        More_Data = input('enter No to quit students entry,enter other values to continue entery')
        
        if Students_id in D:
            print('students_id already exist')
        
                
        
        
        else:
            D[Students_id] = Marks_sheet.split(',')

        if More_Data.lower() == 'no':

            return D
        
                     

In [3]:
#students_Data = Students_info()

In [ ]:
def Arg_func(D):
    argmax={}
    
    for x in D:
        L = D[x]
        s = 0
        for marks in L:
            s = s + int(marks)
            Avg_max =s//len(marks)
        
            argmax[x]=Avg_max
            #sorted(argmax.items(),key = lambda x:x[0])
    #return argmax
            print('the average of students_id:',x,'is',argmax[x])
#the for loops work in a function as saying, after the iteration has been done, give me the final answer by printing 
# or returning a function


In [ ]:
#argmaxs = argmax.items()
#sorted(argmaxs)
sorted(argmax.items(),key = lambda x:x[0])
       #sort(key = lambda x

In [ ]:
Arg_values = Arg_func(students_Data)

In [ ]:
F = {45: ['76', '67', '98', '100'],
 51: ['64', '72', '81', '97'],
 53: ['45', '67', '87', '45']}

In [ ]:
Arg_values

In [ ]:
argmax = {}

In [ ]:
for x in F:
    L = F[x]
    s = 0
    for marks in L:
        s = s + int(marks)
        Avg_max =s/len(marks)
    argmax[x]=Avg_max
print(argmax)
    

In [ ]:
L=[]
p=[]


for i,j in F.items():
#argmax[i]= sum(float(j))/len(j)
#print('the average score of students_id :',i,'is')


In [ ]:
L=[]
p=[]


for i,j in F.items():
    p.append(j)
print(p)

In [ ]:
#print('the average score of students_id :',i,'is'

In [ ]:
type(p[0])

In [ ]:
List_3 = [[23,20,23],[324,34,45,5],[23,2,34]]

In [ ]:
List_3
list_4 = []

In [ ]:
List_3

In [ ]:
List_3


In [ ]:
list_2 = ['Ade','Gbenga','Tayo']

In [ ]:
list_4

In [ ]:
Dimp = {}
for j in List_3:
    B_n = j
    sum_ = 0
    for k in B_n:
        sum_=sum_ + k
        Average = sum_/len(B_n)
    list_4.append(Average)
for i,j in zip(list_2,list_4):
    Dimp[i]=j
    print('the Average score of',i,'is',Dimp[i] )
    
    
        
        
        

In [ ]:
#program to take many inputs at the same time


In [ ]:
#program to take many inputs at the same time
# and to return the average value of the name entered

D = {}
timp_name = []
timp_Avg = []
for _ in range(int(input())):
    
    info_ = [input('please enter the values in the format BME,SCORE,SCORES,....,no space in the last entry of the input :' )]
   
    
    for i in info_:
    
        timp = i.split(" ")
        timp_name.append(timp[0])
        value_score = timp[1:]
        sum = 0
        for x in value_score:
            sum = sum + int(x)
            avg = sum//len(value_score)
        timp_Avg.append(avg)
  
    for i,j in zip(timp_name,timp_Avg):
        D[i]=j        
check_ma = input('which name are you checking:')
if check_ma in D:
    print(' the average score of',check_ma,'is',D[check_ma])      
else:
    print('the name is not in the current index')
  

In [ ]:
n = int(input())
student_marks = {}
for _ in range(n):
    name, *line = input().split()
    scores = list(map(float, line))
    sum = 0
    for i in scores:
        sum = sum + i
        Avg = sum/len(scores)
    student_marks[name] = Avg
query_name = input()
if query_name in student_marks:
    print(student_marks[query_name])
        

In [ ]:
A = (456 +98 +87 +56)

In [ ]:
#print("%.3f"% A)

In [ ]:
float(23)/3

In [ ]:
list_2 = 45

In [ ]:
if __name__ == '__main__':
    n = int(input())
    student_marks = {}
    for _ in range(n):
        name, *line = input().split()
        scores = list(map(float, line))
        sum = 0
        for i in scores:
            sum = sum + i
            Avg = round(sum/len(scores),2)
        student_marks[name] = Avg
    query_name = input()
    if query_name in student_marks:
        print(student_marks[query_name])
        
        

In [ ]:
from collections import Counter

In [ ]:
 (34 +54 +45+ 45+ 45+ 45+ 23+ 67+ 78+ 56+ 45)//11

In [ ]:
timp_Avg

In [ ]:
len(A)

In [ ]:
sum = 0
for i in A:
    sum = sum + int(i) 
print(sum)
    

In [ ]:
check_ma in timp_name

In [ ]:
timp_name

In [ ]:
type(timp_name[0])

In [ ]:
timp_name

In [ ]:
for i in info_:
    timp = i.split(" ")
    timp_name = [timp[0]]
timp_name   
    

In [ ]:
timp

In [ ]:
timp_name

In [ ]:
list_1 = [2,3,2,4,4,5,2,5,4,1]
from collections import Counter

In [ ]:
D = {}
for i in list_1:
    D[i]=list_1.count(i)

In [ ]:
dict(sorted(D.items(),key = lambda x:x[0],reverse = False))

In [ ]:
Counter(list_1)

In [ ]:
# I need to write programs that will give me the no of commands to enter and it will input all this commands in 

In [ ]:
list_1 = []

In [ ]:
for _ in range(int(input())):
    for i in list_1:
        
        
   
        Name_of_command1 =list_1.(input('what is the first command?: '))
        
  
  
    


In [ ]:
tex = 'jnkfkdff'

In [ ]:
tex.split?

In [ ]:
list_1.insert(2,0)

In [ ]:
list_1

In [ ]:
#this program helps to perform many inputs in python, the input saved with variable user_input takes a string 
#convert split it and then the if loop is used to check for the type of lists method.
List_1 = []
for _ in range(int(input())):
    
    user_input = input().strip().split(sep =None)
    if user_input[0] == 'insert':
        List_1.insert(int(user_input[1]),int(user_input[2]))
    elif user_input[0] == 'append':
        List_1.append(int(user_input[1]))
    elif user_input[0]=='print':
            print(List_1)
    elif user_input[0] == 'remove':
        List_1.remove(int(user_input[1]))
    elif user_input[0] == 'pop':
        List_1.pop()
    elif user_input[0] == 'reverse':
        List_1.reverse()
    elif user_input[0] == 'sort':
        List_1.sort()
        
        #the result of the inputs can be find below,this has been run and tested,it is working out fine
        
        
            
            

In [ ]:
12
insert 0 5
insert 1 10
insert 0 6
print
remove 6
append 9
append 1
sort
print
pop
reverse
print

In [ ]:
#text_2 = 'let the earth proclaim that christ is lord'

In [ ]:
#text_3 = text_1 + (text_2)

In [ ]:
list_1 =[]

In [ ]:
listr_1 = [2,4,5,10,12]

In [ ]:
List_2 = [23,45,56,78,3,2]

In [ ]:
texT_1 = input('please which of the list do u wanna add? :')
    

In [ ]:
#"("+",.join(args))"

In [ ]:
ibk_1 = input('How old are you ibk:')
if ibk_1 > '23':
    print('ibk, you are old o, imagine your age is',ibk_1)
elif int(ibk_1) < 23 and int(ibk_1) > 20:
    
    print('you are still a baby')

elif ibk_1 =='19':
    Ibk_married_yr = int(ibk_1) + 10
    print("ibk_1 will be getting married in",Ibk_married_yr,"years")


In [ ]:
 n = int(input())
for _ in range(n):
    integer_list = map(int, input().split())
    t = tuple(integer_list)
    print(hash(t))
        

In [ ]:
 n = int(input())
for _ in range(n):
    integer_list = map(int, input().split())
    t = tuple(integer_list)
    print(hash(t))
        

In [ ]:
first_name = input()
last_name = input()
print("hello",first_name,last_name+"!" "you just delved into python")

In [ ]:
print(f"Hello {first_name} {last_name}! You just delved into python.")

In [ ]:
nim = 'when' ,first_name

In [ ]:
str(nim)

In [ ]:
print(f" hello,{first_name} {last_name}! you just delved into python")

In [ ]:
sample_tupple = []
for _ in range(int(input())):
    
    sample_tupple.append(str(input()))
                         


In [ ]:
hash(tuple(sample_tupple))

In [ ]:
print(map(int,sample_tupple))

In [ ]:
tuple(str(sample_tupple).strip().split())

In [ ]:
hash(tuple(str(list_num)))

In [ ]:
for _ in range(len(input())):
    output = map(int,input())
    

In [ ]:
bump = [2*i for i in range(10)]

In [ ]:
bump

In [ ]:
list_2 = []
for _ in range(int(input())):
    bump= input().split()
    bumps = list(map(int,bump))
    
    list_2.append(bumps)


    
 
        

In [ ]:
list_2

In [ ]:
k = []
kimpe_ = ['3564','45','67','65','567']

In [ ]:
output = '1 2'.strip().split()

In [ ]:
outsss= tuple(map(int,output))

In [ ]:
n = int(input())
integer_list =tuple(map(int,input().strip().split()))
        
print(hash(integer_list))
        
    

In [ ]:
for _ in range(int(input())):
    print (_, end = " ")
for _ in range(int(input())):
    
    output = input().split(sep = None)
    if output[0] =='print':
        print(list_2)
    elif output[0]=='append':
        list_2.append(int(output[1]))
    elif output[0] == 'remove' and int(output[1]) not in list_2:
        break
    elif output[0] == 'remove' and int(output[1]) in list_2:
        list_2.remove(int(output[1]))
print(list_2)   
    
    
    
        
    
    

In [ ]:
for _ in range(int(input())):
    print(_, end = " ")

In [ ]:
for i in range(20):
    print(i,end =" ")

In [8]:
text ='ABCDCDC'

In [10]:
text.count('CD')

2

In [19]:
def count_substring(string, sub_string):
    return string.count(sub_string)


In [20]:
string = input().strip()
sub_string = input().strip()

ABCDCDC
CDC


In [21]:
count_substring(string, sub_string)

1

In [ ]:
#in this code, I am define a class object named iphone and try to define some of its attributes, I created the instances
# of the class iphone iphone_11_max with a special type of attributes
# from my observation, the class object iphone needs to be created as a bluebrint for other type of iphones that will be produced
#the class object is a user_built function
class iphone:
    
    "trying to define the blueprint of iphone and using the special instance type  of iphone 10 max" 
    "when accessing the class object, ensure you use .__class___. method to access it"
    #whe
    
    type = 'iphone 10 max'
    bimp = 24700,45
    def __init__(self,camera,software_update):
        self.camera = camera
        self.software_update = software_update
        
      
    #Note, when defining the attributes of iphone(using __init__) method, it is possible the iphone uses 
    #alot of attributes when definning it.
    
    # we define two methods in the program above, methods helps you to access functionalities of the iphone type created
    def Sarri_func(self,sarri_check):
        print('pls sarri, can you help play the song by',sarri_check)
        
    def weather_check(self,weather):
        return "the weather currently is",weather
    
iphone_11_max = iphone("led_camera","software_10")
    

In [31]:
print(f"iphone_11 max uses camera type :{iphone_11_max.camera} and the recent ios update of : {iphone_11_max.software_update}, this makes it suitable for"
"new users to work with")

iphone_11 max uses camera type :led_camera and the recent ios update of : software_10, this makes it suitable fornew users to work with


In [35]:
#print('the type of iphone  we are working on is {}'.format(iphone_11_max.__class__.type))

the type of iphone  we are working on is iphone 10 max


In [54]:
#rint('the iphone type we are building is',iphone_11_max.camera)

In [53]:
#iphone_11_max.software_update

In [52]:
#iphone_11_max.__class__.type,iphone_11_max.__class__.bimp

In [75]:
iphone_11_max.weather_check("30F")

('the weather currently is', '30F')

In [80]:
iphone_11_max.Sarri_func('Nathaniel_bassey')

pls sarri, can you help play the song by Nathaniel_bassey


In [ ]:
,camera,software_update

In [50]:
#Child class
class iphone_new_gen(iphone):
    
    def __init__(camera,software_update):
        
        super().__init__(camera,software_update)
        print('this is a new class defined under parent class')
        
    def new_func(self):
        print('Hello God, you boy is here again')
        
    def kimpe(self):
        return "Jesus has come to save us"
        
        
        

In [ ]:
# the self keyword triggers the methods of the instance from the object class

In [58]:
#Data Encapsulation--we can restrict the access to methods and variables.This prevents data from direct modification

In [53]:
iphonbe_13 = iphone_new_gen('camp')

this is a new class defined under parent class


In [54]:
iphonbe_13.Sarri_func('bimsx')

pls sarri, can you help play the song by bimsx


In [55]:
iphonbe_13.new_func()

Hello God, you boy is here again


In [ ]:
#2 things to do today:
# to work on classes functions


In [25]:
import numpy

In [28]:
A = numpy.array([[2,3,4,5],[3,3,5,6]])

In [34]:
A.mean(axis = 1,dtype = int)

array([3, 4])

In [33]:
A.shape

(2, 4)

In [43]:
for i in A:
    print(i)

[2 3 4 5]
[3 3 5 6]


In [59]:
#trying to define a class that stores the value of prices of goods
#we want an output that always spills out anytime the price us above 1000

In [184]:
class Computer:
    
    pass
    

    
    def __init__(self):
        
        self.__Maxprice = 1000
        
    def Sell(self):
        print('the selling price is now : {}'.format(self.__Maxprice))
       
    
    def Set_price(self,price):
        self.__Maxprice = price
        
        

In [196]:
# when you need to  modify the attributes, you can define a methode that can do so, in the above codes ,
#The Set_price did a nice Job in doing that

In [204]:
class Parrot:
    
    def fly(self):
        print('the parrot does fly')
        
    def sing(self):
        print("can it sing also?")
        
class Pengui:
    
    def fly(self):
        print('the penguins cant fly')
        
    def hungry(self):
        print('is the pengui hungry sometimes')
        
def fly_test(bird):
    return bird.fly()

#The above function is called polymorphism, it allows two different classes to return the same fly method

In [205]:
Bug = Parrot()
pimgun = Pengui()

In [206]:
jimp,simpu = fly_test(Bug),fly_test(pimgun)

the parrot does fly
the penguins cant fly


In [207]:
D = {'jimp': 200,'sdhbjsd':'sdbh'}

In [209]:
D.setdefault('puppsy')

In [210]:
D

{'jimp': 200, 'sdhbjsd': 'sdbh', 'puppsy': None}

In [213]:
k = [x for x in D]

In [216]:
k.pop()

'puppsy'

In [217]:
k

['jimp', 'sdhbjsd']

In [220]:
A = 2 + 3 == 4

In [224]:
list_1 = [[4],[45],[67]]

In [228]:
''.join(list(map(str,list_1)))

'[4][45][67]'

In [236]:
tim = 'shdbsd'

In [247]:
print('**',tim.center(5),'**',sep= '')

**shdbsd**


In [239]:
len('shdbsd')

6

In [251]:
password = input('please enter your password here:')
print('**',password,'**',sep ='')

please enter your password here:Rotimi Kolawole
**Rotimi Kolawole**


In [262]:
[2,23,34,54][::-1]
#this reverses the list

[54, 34, 23, 2]

In [270]:
x = 10

def func(x):
    return 23/5



In [273]:
x = 'abcd'
for i in x:
    print(i.upper())

A
B
C
D
